export const TROPHY_DETAILS: Record<string, any> = {
  the_juggernaut: {
    id: 'the_juggernaut',
    title: 'THE JUGGERNAUT',
    rarity: 'LEGENDARY',
    subtitle: '100 Fast Pushups',
    description: 'Execute 100 relentless pushups in a single session. Must be completed in under 9 minutes.',
    target: 100,
    unit: '',
    image: require('../assets/achievement_badges/The Juggernaut_badge.png'),
    accentColor: '#EF4444', 
  },
  the_statue: {
    id: 'the_statue',
    title: 'THE STATUE',
    rarity: 'LEGENDARY',
    subtitle: '5 Min Flawless Plank',
    description: 'Hold a flawless plank for 5 full minutes. Total session time cannot exceed 7.5 minutes.',
    target: 300, 
    unit: 's',
    image: require('../assets/achievement_badges/The Statue_badge.png'),
    accentColor: '#38BDF8', 
  },
  the_surgeon: {
    id: 'the_surgeon',
    title: 'THE SURGEON',
    rarity: 'EPIC',
    subtitle: '95% Form Accuracy',
    description: 'Complete a 50+ rep workout with 95% or higher mechanical accuracy.',
    target: 95,
    unit: '%',
    image: require('../assets/achievement_badges/The Surgeon_badge.png'),
    accentColor: '#22C55E', 
  },
  gravity_defiant: {
    id: 'gravity_defiant',
    title: 'GRAVITY DEFIANT',
    rarity: 'LEGENDARY',
    subtitle: '10,000 Lifetime Reps',
    description: 'Accumulate a massive 10,000 total valid reps across your lifetime.',
    target: 10000,
    unit: '',
    image: require('../assets/achievement_badges/Gravity Defiant_badge.png'),
    accentColor: '#A855F7', 
  },
  the_centurion: {
    id: 'the_centurion',
    title: 'THE CENTURION',
    rarity: 'LEGENDARY',
    subtitle: '100 Total Workouts',
    description: 'Prove your ultimate dedication by completing 100 total workouts.',
    target: 100,
    unit: '',
    image: require('../assets/achievement_badges/The Centurion_badge.png'),
    accentColor: '#F59E0B', 
  },
};
