export const ALL_EMOJIS = [
  // Smileys & Emotion
  { emoji: "😀", keywords: ["grinning", "face", "smile", "happy", "joy"] },
  { emoji: "😂", keywords: ["face", "tears", "joy", "laugh", "cry"] },
  { emoji: "🤣", keywords: ["rolling", "floor", "laughing", "rofl"] },
  { emoji: "😊", keywords: ["smiling", "face", "eyes", "happy", "blush"] },
  { emoji: "🥰", keywords: ["smiling", "face", "hearts", "love", "adore"] },
  { emoji: "😍", keywords: ["smiling", "face", "heart", "eyes", "love"] },
  { emoji: "😎", keywords: ["smiling", "face", "sunglasses", "cool"] },
  { emoji: "😭", keywords: ["loudly", "crying", "face", "sad", "tears"] },
  { emoji: "🥺", keywords: ["pleading", "face", "puppy", "eyes", "beg"] },
  { emoji: "🤔", keywords: ["thinking", "face", "hmm", "ponder"] },
  { emoji: "🤫", keywords: ["shushing", "face", "quiet", "shh"] },
  { emoji: "🤬", keywords: ["face", "symbols", "mouth", "cursing", "angry"] },
  { emoji: "🤯", keywords: ["exploding", "head", "mind", "blown"] },
  { emoji: "🥶", keywords: ["cold", "face", "freezing", "ice"] },
  { emoji: "🥵", keywords: ["hot", "face", "sweating", "heat"] },
  { emoji: "😇", keywords: ["smiling", "face", "halo", "angel"] },
  { emoji: "🥳", keywords: ["partying", "face", "celebration", "party"] },
  { emoji: "🤡", keywords: ["clown", "face", "joke", "fool"] },
  { emoji: "👻", keywords: ["ghost", "boo", "scary"] },
  { emoji: "👽", keywords: ["alien", "ufo", "space"] },
  { emoji: "👾", keywords: ["alien", "monster", "game", "retro"] },
  { emoji: "🤖", keywords: ["robot", "bot", "ai"] },
  { emoji: "💩", keywords: ["pile", "poo", "shit", "crap"] },
  // Gestures & Body Parts
  { emoji: "👍", keywords: ["thumbs", "up", "yes", "good", "approve"] },
  { emoji: "👎", keywords: ["thumbs", "down", "no", "bad"] },
  { emoji: "✌️", keywords: ["victory", "hand", "peace", "two"] },
  { emoji: "🤞", keywords: ["crossed", "fingers", "luck", "hope"] },
  { emoji: "🤟", keywords: ["love", "you", "gesture", "hand"] },
  { emoji: "🤘", keywords: ["sign", "horns", "rock", "metal"] },
  { emoji: "🤙", keywords: ["call", "me", "hand", "shaka", "hang", "loose"] },
  { emoji: "👋", keywords: ["waving", "hand", "hello", "hi", "bye"] },
  { emoji: "👏", keywords: ["clapping", "hands", "applause", "bravo"] },
  { emoji: "🙌", keywords: ["raising", "hands", "hooray", "celebration"] },
  { emoji: "👐", keywords: ["open", "hands", "hug"] },
  { emoji: "🤲", keywords: ["palms", "up", "together", "pray"] },
  { emoji: "🤝", keywords: ["handshake", "deal", "agree"] },
  { emoji: "🙏", keywords: ["folded", "hands", "pray", "please", "thanks"] },
  { emoji: "💪", keywords: ["flexed", "biceps", "strong", "muscle", "workout"] },
  { emoji: "🦾", keywords: ["mechanical", "arm", "robot", "cyborg", "strong"] },
  { emoji: "🦵", keywords: ["leg", "kick"] },
  { emoji: "🦶", keywords: ["foot", "kick", "stomp"] },
  { emoji: "👀", keywords: ["eyes", "look", "see", "watch"] },
  { emoji: "🧠", keywords: ["brain", "smart", "think", "mind"] },
  { emoji: "🫀", keywords: ["anatomical", "heart", "health", "life"] },
  { emoji: "🫁", keywords: ["lungs", "breath", "health"] },
  // People & Fantasy
  { emoji: "👶", keywords: ["baby", "child", "young"] },
  { emoji: "👧", keywords: ["girl", "child", "young"] },
  { emoji: "👦", keywords: ["boy", "child", "young"] },
  { emoji: "👩", keywords: ["woman", "female", "adult"] },
  { emoji: "👨", keywords: ["man", "male", "adult"] },
  { emoji: "🧑", keywords: ["person", "adult", "human"] },
  { emoji: "👵", keywords: ["old", "woman", "elderly"] },
  { emoji: "👴", keywords: ["old", "man", "elderly"] },
  { emoji: "👮", keywords: ["police", "officer", "cop"] },
  { emoji: "👷", keywords: ["construction", "worker", "builder"] },
  { emoji: "💂", keywords: ["guard", "soldier"] },
  { emoji: "🕵️", keywords: ["detective", "spy", "sleuth"] },
  { emoji: "👩‍⚕️", keywords: ["woman", "health", "worker", "doctor", "nurse"] },
  { emoji: "👨‍⚕️", keywords: ["man", "health", "worker", "doctor", "nurse"] },
  { emoji: "👩‍🌾", keywords: ["woman", "farmer", "agriculture"] },
  { emoji: "👨‍🌾", keywords: ["man", "farmer", "agriculture"] },
  { emoji: "👩‍🍳", keywords: ["woman", "cook", "chef", "food"] },
  { emoji: "👨‍🍳", keywords: ["man", "cook", "chef", "food"] },
  { emoji: "👩‍🎓", keywords: ["woman", "student", "graduate", "school"] },
  { emoji: "👨‍🎓", keywords: ["man", "student", "graduate", "school"] },
  { emoji: "👩‍🎤", keywords: ["woman", "singer", "star", "music"] },
  { emoji: "👨‍🎤", keywords: ["man", "singer", "star", "music"] },
  { emoji: "👩‍🏫", keywords: ["woman", "teacher", "school", "education"] },
  { emoji: "👨‍🏫", keywords: ["man", "teacher", "school", "education"] },
  { emoji: "👩‍🏭", keywords: ["woman", "factory", "worker", "industry"] },
  { emoji: "👨‍🏭", keywords: ["man", "factory", "worker", "industry"] },
  { emoji: "👩‍💻", keywords: ["woman", "technologist", "coder", "developer", "hacker"] },
  { emoji: "👨‍💻", keywords: ["man", "technologist", "coder", "developer", "hacker"] },
  { emoji: "👩‍💼", keywords: ["woman", "office", "worker", "business", "manager"] },
  { emoji: "👨‍💼", keywords: ["man", "office", "worker", "business", "manager"] },
  { emoji: "👩‍🔧", keywords: ["woman", "mechanic", "fix", "repair"] },
  { emoji: "👨‍🔧", keywords: ["man", "mechanic", "fix", "repair"] },
  { emoji: "👩‍🔬", keywords: ["woman", "scientist", "chemistry", "lab"] },
  { emoji: "👨‍🔬", keywords: ["man", "scientist", "chemistry", "lab"] },
  { emoji: "👩‍🎨", keywords: ["woman", "artist", "paint", "draw"] },
  { emoji: "👨‍🎨", keywords: ["man", "artist", "paint", "draw"] },
  { emoji: "👩‍🚒", keywords: ["woman", "firefighter", "fire"] },
  { emoji: "👨‍🚒", keywords: ["man", "firefighter", "fire"] },
  { emoji: "👩‍✈️", keywords: ["woman", "pilot", "plane", "fly"] },
  { emoji: "👨‍✈️", keywords: ["man", "pilot", "plane", "fly"] },
  { emoji: "👩‍🚀", keywords: ["woman", "astronaut", "space", "rocket"] },
  { emoji: "👨‍🚀", keywords: ["man", "astronaut", "space", "rocket"] },
  { emoji: "👩‍⚖️", keywords: ["woman", "judge", "law", "justice"] },
  { emoji: "👨‍⚖️", keywords: ["man", "judge", "law", "justice"] },
  { emoji: "🦸", keywords: ["superhero", "hero", "power"] },
  { emoji: "🦹", keywords: ["supervillain", "villain", "bad"] },
  { emoji: "🧙", keywords: ["mage", "wizard", "witch", "magic"] },
  { emoji: "🧚", keywords: ["fairy", "wings", "magic"] },
  { emoji: "🧛", keywords: ["vampire", "dracula", "blood"] },
  { emoji: "🧜", keywords: ["merperson", "mermaid", "merman", "sea"] },
  { emoji: "🧝", keywords: ["elf", "lotr", "fantasy"] },
  { emoji: "🧞", keywords: ["genie", "lamp", "wish"] },
  { emoji: "🧟", keywords: ["zombie", "undead", "monster"] },
  { emoji: "💆", keywords: ["person", "getting", "massage", "relax"] },
  { emoji: "💇", keywords: ["person", "getting", "haircut", "salon"] },
  { emoji: "🚶", keywords: ["person", "walking", "walk"] },
  { emoji: "🧍", keywords: ["person", "standing", "stand"] },
  { emoji: "🧎", keywords: ["person", "kneeling", "kneel"] },
  { emoji: "🏃", keywords: ["person", "running", "run", "fast"] },
  { emoji: "💃", keywords: ["woman", "dancing", "dance", "party"] },
  { emoji: "🕺", keywords: ["man", "dancing", "dance", "party"] },
  { emoji: "🕴️", keywords: ["man", "in", "suit", "levitating", "business"] },
  { emoji: "👯", keywords: ["people", "with", "bunny", "ears", "party", "girls"] },
  { emoji: "🧖", keywords: ["person", "in", "steamy", "room", "sauna", "spa"] },
  { emoji: "🧗", keywords: ["person", "climbing", "climb", "boulder"] },
  { emoji: "🤺", keywords: ["person", "fencing", "fence", "sword"] },
  { emoji: "🏇", keywords: ["horse", "racing", "race", "jockey"] },
  { emoji: "⛷️", keywords: ["skier", "ski", "snow"] },
  { emoji: "🏂", keywords: ["snowboarder", "snowboard", "snow"] },
  { emoji: "🏌️", keywords: ["person", "golfing", "golf", "swing"] },
  { emoji: "🏄", keywords: ["person", "surfing", "surf", "wave"] },
  { emoji: "🚣", keywords: ["person", "rowing", "boat", "water"] },
  { emoji: "🏊", keywords: ["person", "swimming", "swim", "pool"] },
  { emoji: "⛹️", keywords: ["person", "bouncing", "ball", "basketball"] },
  { emoji: "🏋️", keywords: ["person", "lifting", "weights", "workout", "gym"] },
  { emoji: "🚴", keywords: ["person", "biking", "bike", "bicycle"] },
  { emoji: "🚵", keywords: ["person", "mountain", "biking", "bike", "bicycle"] },
  { emoji: "🤸", keywords: ["person", "cartwheeling", "gymnastics", "flip"] },
  { emoji: "🤼", keywords: ["people", "wrestling", "wrestle", "fight"] },
  { emoji: "🤽", keywords: ["person", "playing", "water", "polo", "pool"] },
  { emoji: "🤾", keywords: ["person", "playing", "handball", "ball"] },
  { emoji: "🤹", keywords: ["person", "juggling", "juggle", "circus"] },
  { emoji: "🧘", keywords: ["person", "in", "lotus", "position", "yoga", "meditate"] },
  // Animals & Nature
  { emoji: "🐶", keywords: ["dog", "face", "pet", "puppy"] },
  { emoji: "🐱", keywords: ["cat", "face", "pet", "kitten"] },
  { emoji: "🐭", keywords: ["mouse", "face", "animal"] },
  { emoji: "🐹", keywords: ["hamster", "face", "pet"] },
  { emoji: "🐰", keywords: ["rabbit", "face", "bunny"] },
  { emoji: "🦊", keywords: ["fox", "face", "animal"] },
  { emoji: "🐻", keywords: ["bear", "face", "animal"] },
  { emoji: "🐼", keywords: ["panda", "face", "animal"] },
  { emoji: "🐨", keywords: ["koala", "animal"] },
  { emoji: "🐯", keywords: ["tiger", "face", "animal"] },
  { emoji: "🦁", keywords: ["lion", "face", "animal", "king"] },
  { emoji: "🐮", keywords: ["cow", "face", "animal"] },
  { emoji: "🐷", keywords: ["pig", "face", "animal"] },
  { emoji: "🐸", keywords: ["frog", "face", "animal", "toad"] },
  { emoji: "🐵", keywords: ["monkey", "face", "animal"] },
  { emoji: "🙈", keywords: ["see", "no", "evil", "monkey", "blind"] },
  { emoji: "🙉", keywords: ["hear", "no", "evil", "monkey", "deaf"] },
  { emoji: "🙊", keywords: ["speak", "no", "evil", "monkey", "mute"] },
  { emoji: "🐒", keywords: ["monkey", "animal"] },
  { emoji: "🦍", keywords: ["gorilla", "animal", "ape"] },
  { emoji: "🦧", keywords: ["orangutan", "animal", "ape"] },
  { emoji: "🐕", keywords: ["dog", "animal", "pet"] },
  { emoji: "🦮", keywords: ["guide", "dog", "animal", "blind"] },
  { emoji: "🐩", keywords: ["poodle", "dog", "animal", "pet"] },
  { emoji: "🐺", keywords: ["wolf", "face", "animal"] },
  { emoji: "🦊", keywords: ["fox", "face", "animal"] },
  { emoji: "🦝", keywords: ["raccoon", "animal"] },
  { emoji: "🐱", keywords: ["cat", "face", "pet"] },
  { emoji: "🐈", keywords: ["cat", "animal", "pet"] },
  { emoji: "🦁", keywords: ["lion", "face", "animal"] },
  { emoji: "🐯", keywords: ["tiger", "face", "animal"] },
  { emoji: "🐅", keywords: ["tiger", "animal"] },
  { emoji: "🐆", keywords: ["leopard", "animal"] },
  { emoji: "🐴", keywords: ["horse", "face", "animal"] },
  { emoji: "🐎", keywords: ["horse", "animal", "race"] },
  { emoji: "🦄", keywords: ["unicorn", "face", "animal", "magic"] },
  { emoji: "🦓", keywords: ["zebra", "animal"] },
  { emoji: "🦌", keywords: ["deer", "animal"] },
  { emoji: "🦬", keywords: ["bison", "animal"] },
  { emoji: "🐮", keywords: ["cow", "face", "animal"] },
  { emoji: "🐂", keywords: ["ox", "animal"] },
  { emoji: "🐃", keywords: ["water", "buffalo", "animal"] },
  { emoji: "🐄", keywords: ["cow", "animal"] },
  { emoji: "🐷", keywords: ["pig", "face", "animal"] },
  { emoji: "🐖", keywords: ["pig", "animal"] },
  { emoji: "🐗", keywords: ["boar", "animal"] },
  { emoji: "🐽", keywords: ["pig", "nose", "animal"] },
  { emoji: "🐏", keywords: ["ram", "animal"] },
  { emoji: "🐑", keywords: ["ewe", "sheep", "animal"] },
  { emoji: "🐐", keywords: ["goat", "animal"] },
  { emoji: "🐪", keywords: ["camel", "animal"] },
  { emoji: "🐫", keywords: ["two-hump", "camel", "animal"] },
  { emoji: "🦙", keywords: ["llama", "animal"] },
  { emoji: "🦒", keywords: ["giraffe", "animal"] },
  { emoji: "🐘", keywords: ["elephant", "animal"] },
  { emoji: "🦣", keywords: ["mammoth", "animal"] },
  { emoji: "🦏", keywords: ["rhinoceros", "animal"] },
  { emoji: "🦛", keywords: ["hippopotamus", "animal"] },
  { emoji: "🐭", keywords: ["mouse", "face", "animal"] },
  { emoji: "🐁", keywords: ["mouse", "animal"] },
  { emoji: "🐀", keywords: ["rat", "animal"] },
  { emoji: "🐹", keywords: ["hamster", "face", "animal"] },
  { emoji: "🐰", keywords: ["rabbit", "face", "animal"] },
  { emoji: "🐇", keywords: ["rabbit", "animal"] },
  { emoji: "🐿️", keywords: ["chipmunk", "animal"] },
  { emoji: "🦫", keywords: ["beaver", "animal"] },
  { emoji: "🦔", keywords: ["hedgehog", "animal"] },
  { emoji: "🦇", keywords: ["bat", "animal", "vampire"] },
  { emoji: "🐻", keywords: ["bear", "face", "animal"] },
  { emoji: "🐻‍❄️", keywords: ["polar", "bear", "animal"] },
  { emoji: "🐨", keywords: ["koala", "animal"] },
  { emoji: "🐼", keywords: ["panda", "face", "animal"] },
  { emoji: "🦥", keywords: ["sloth", "animal"] },
  { emoji: "🦦", keywords: ["otter", "animal"] },
  { emoji: "🦨", keywords: ["skunk", "animal"] },
  { emoji: "🦘", keywords: ["kangaroo", "animal"] },
  { emoji: "🦡", keywords: ["badger", "animal"] },
  { emoji: "🐾", keywords: ["paw", "prints", "animal"] },
  { emoji: "🦃", keywords: ["turkey", "animal", "bird"] },
  { emoji: "🐔", keywords: ["chicken", "animal", "bird"] },
  { emoji: "🐓", keywords: ["rooster", "animal", "bird"] },
  { emoji: "🐣", keywords: ["hatching", "chick", "animal", "bird"] },
  { emoji: "🐤", keywords: ["baby", "chick", "animal", "bird"] },
  { emoji: "🐥", keywords: ["front-facing", "baby", "chick", "animal", "bird"] },
  { emoji: "🐦", keywords: ["bird", "animal"] },
  { emoji: "🐧", keywords: ["penguin", "animal", "bird"] },
  { emoji: "🕊️", keywords: ["dove", "animal", "bird", "peace"] },
  { emoji: "🦅", keywords: ["eagle", "animal", "bird"] },
  { emoji: "🦆", keywords: ["duck", "animal", "bird"] },
  { emoji: "🦢", keywords: ["swan", "animal", "bird"] },
  { emoji: "🦉", keywords: ["owl", "animal", "bird"] },
  { emoji: "🦤", keywords: ["dodo", "animal", "bird"] },
  { emoji: "🪶", keywords: ["feather", "bird"] },
  { emoji: "🦩", keywords: ["flamingo", "animal", "bird"] },
  { emoji: "🦚", keywords: ["peacock", "animal", "bird"] },
  { emoji: "🦜", keywords: ["parrot", "animal", "bird"] },
  { emoji: "🐸", keywords: ["frog", "face", "animal"] },
  { emoji: "🐊", keywords: ["crocodile", "animal", "reptile"] },
  { emoji: "🐢", keywords: ["turtle", "animal", "reptile"] },
  { emoji: "🦎", keywords: ["lizard", "animal", "reptile"] },
  { emoji: "🐍", keywords: ["snake", "animal", "reptile"] },
  { emoji: "🐲", keywords: ["dragon", "face", "animal", "myth"] },
  { emoji: "🐉", keywords: ["dragon", "animal", "myth"] },
  { emoji: "🦕", keywords: ["sauropod", "dinosaur", "animal"] },
  { emoji: "🦖", keywords: ["t-rex", "dinosaur", "animal"] },
  { emoji: "🐳", keywords: ["spouting", "whale", "animal", "sea"] },
  { emoji: "🐋", keywords: ["whale", "animal", "sea"] },
  { emoji: "🐬", keywords: ["dolphin", "animal", "sea"] },
  { emoji: "🦭", keywords: ["seal", "animal", "sea"] },
  { emoji: "🐟", keywords: ["fish", "animal", "sea"] },
  { emoji: "🐠", keywords: ["tropical", "fish", "animal", "sea"] },
  { emoji: "🐡", keywords: ["blowfish", "animal", "sea"] },
  { emoji: "🦈", keywords: ["shark", "animal", "sea"] },
  { emoji: "🐙", keywords: ["octopus", "animal", "sea"] },
  { emoji: "🦑", keywords: ["squid", "animal", "sea"] },
  { emoji: "🦐", keywords: ["shrimp", "animal", "sea"] },
  { emoji: "🦞", keywords: ["lobster", "animal", "sea"] },
  { emoji: "🦀", keywords: ["crab", "animal", "sea"] },
  { emoji: "🐡", keywords: ["blowfish", "animal", "sea"] },
  { emoji: "🐌", keywords: ["snail", "animal", "bug"] },
  { emoji: "🦋", keywords: ["butterfly", "animal", "bug"] },
  { emoji: "🐛", keywords: ["bug", "animal", "insect"] },
  { emoji: "🐜", keywords: ["ant", "animal", "insect"] },
  { emoji: "🐝", keywords: ["honeybee", "animal", "insect"] },
  { emoji: "🪲", keywords: ["beetle", "animal", "insect"] },
  { emoji: "🐞", keywords: ["ladybug", "animal", "insect"] },
  { emoji: "🦗", keywords: ["cricket", "animal", "insect"] },
  { emoji: "🪳", keywords: ["cockroach", "animal", "insect"] },
  { emoji: "🕷️", keywords: ["spider", "animal", "insect"] },
  { emoji: "🕸️", keywords: ["spider", "web", "insect"] },
  { emoji: "🦂", keywords: ["scorpion", "animal", "insect"] },
  { emoji: "🦟", keywords: ["mosquito", "animal", "insect"] },
  { emoji: "🪰", keywords: ["fly", "animal", "insect"] },
  { emoji: "🪱", keywords: ["worm", "animal", "insect"] },
  { emoji: "🦠", keywords: ["microbe", "virus", "bacteria"] },
  { emoji: "💐", keywords: ["bouquet", "flowers", "nature"] },
  { emoji: "🌸", keywords: ["cherry", "blossom", "flower", "nature"] },
  { emoji: "💮", keywords: ["white", "flower", "nature"] },
  { emoji: "🏵️", keywords: ["rosette", "flower", "nature"] },
  { emoji: "🌹", keywords: ["rose", "flower", "nature"] },
  { emoji: "🥀", keywords: ["wilted", "flower", "nature"] },
  { emoji: "🌺", keywords: ["hibiscus", "flower", "nature"] },
  { emoji: "🌻", keywords: ["sunflower", "flower", "nature"] },
  { emoji: "🌼", keywords: ["blossom", "flower", "nature"] },
  { emoji: "🌷", keywords: ["tulip", "flower", "nature"] },
  { emoji: "🌱", keywords: ["seedling", "plant", "nature"] },
  { emoji: "🪴", keywords: ["potted", "plant", "nature"] },
  { emoji: "🌲", keywords: ["evergreen", "tree", "nature"] },
  { emoji: "🌳", keywords: ["deciduous", "tree", "nature"] },
  { emoji: "🌴", keywords: ["palm", "tree", "nature"] },
  { emoji: "🌵", keywords: ["cactus", "plant", "nature"] },
  { emoji: "🌾", keywords: ["sheaf", "of", "rice", "plant", "nature"] },
  { emoji: "🌿", keywords: ["herb", "plant", "nature"] },
  { emoji: "☘️", keywords: ["shamrock", "plant", "nature", "luck"] },
  { emoji: "🍀", keywords: ["four", "leaf", "clover", "plant", "nature", "luck"] },
  { emoji: "🍁", keywords: ["maple", "leaf", "nature", "fall"] },
  { emoji: "🍂", keywords: ["fallen", "leaf", "nature", "fall"] },
  { emoji: "🍃", keywords: ["leaf", "fluttering", "in", "wind", "nature"] },
  // Activities & Sports
  { emoji: "⚽", keywords: ["soccer", "ball", "sport"] },
  { emoji: "🏀", keywords: ["basketball", "sport", "ball"] },
  { emoji: "🏈", keywords: ["american", "football", "sport"] },
  { emoji: "⚾", keywords: ["baseball", "sport"] },
  { emoji: "🥎", keywords: ["softball", "sport"] },
  { emoji: "🎾", keywords: ["tennis", "sport", "ball"] },
  { emoji: "🏐", keywords: ["volleyball", "sport", "ball"] },
  { emoji: "🏉", keywords: ["rugby", "football", "sport"] },
  { emoji: "🥏", keywords: ["flying", "disc", "frisbee", "sport"] },
  { emoji: "🎱", keywords: ["pool", "8", "ball", "sport"] },
  { emoji: "🪀", keywords: ["yo-yo", "toy", "play"] },
  { emoji: "🏓", keywords: ["ping", "pong", "sport"] },
  { emoji: "🏸", keywords: ["badminton", "sport"] },
  { emoji: "🏒", keywords: ["ice", "hockey", "sport"] },
  { emoji: "🏑", keywords: ["field", "hockey", "sport"] },
  { emoji: "🥍", keywords: ["lacrosse", "sport"] },
  { emoji: "🏏", keywords: ["cricket", "sport"] },
  { emoji: "🪃", keywords: ["boomerang", "toy", "play"] },
  { emoji: "🥅", keywords: ["goal", "net", "sport"] },
  { emoji: "⛳", keywords: ["flag", "in", "hole", "golf", "sport"] },
  { emoji: "🪁", keywords: ["kite", "toy", "play"] },
  { emoji: "🏹", keywords: ["bow", "and", "arrow", "archery", "sport"] },
  { emoji: "🎣", keywords: ["fishing", "pole", "sport"] },
  { emoji: "🤿", keywords: ["diving", "mask", "sport"] },
  { emoji: "🥊", keywords: ["boxing", "glove", "sport", "fight"] },
  { emoji: "🥋", keywords: ["martial", "arts", "uniform", "sport"] },
  { emoji: "🎽", keywords: ["running", "shirt", "sport"] },
  { emoji: "🛹", keywords: ["skateboard", "sport"] },
  { emoji: "🛼", keywords: ["roller", "skate", "sport"] },
  { emoji: "🛷", keywords: ["sled", "sport", "snow"] },
  { emoji: "⛸️", keywords: ["ice", "skate", "sport", "snow"] },
  { emoji: "🥌", keywords: ["curling", "stone", "sport", "snow"] },
  { emoji: "🎿", keywords: ["skis", "sport", "snow"] },
  { emoji: "⛷️", keywords: ["skier", "sport", "snow"] },
  { emoji: "🏂", keywords: ["snowboarder", "sport", "snow"] },
  { emoji: "🪂", keywords: ["parachute", "sport"] },
  { emoji: "🏋️", keywords: ["person", "lifting", "weights", "workout", "gym", "sport"] },
  { emoji: "🤼", keywords: ["people", "wrestling", "fight", "sport"] },
  { emoji: "🤸", keywords: ["person", "cartwheeling", "gymnastics", "sport"] },
  { emoji: "⛹️", keywords: ["person", "bouncing", "ball", "basketball", "sport"] },
  { emoji: "🤺", keywords: ["person", "fencing", "sword", "sport"] },
  { emoji: "🤾", keywords: ["person", "playing", "handball", "sport"] },
  { emoji: "🏌️", keywords: ["person", "golfing", "golf", "sport"] },
  { emoji: "🏇", keywords: ["horse", "racing", "sport"] },
  { emoji: "🧘", keywords: ["person", "in", "lotus", "position", "yoga", "meditate"] },
  { emoji: "🏄", keywords: ["person", "surfing", "sport"] },
  { emoji: "🏊", keywords: ["person", "swimming", "sport"] },
  { emoji: "🤽", keywords: ["person", "playing", "water", "polo", "sport"] },
  { emoji: "🚣", keywords: ["person", "rowing", "boat", "sport"] },
  { emoji: "🧗", keywords: ["person", "climbing", "sport"] },
  { emoji: "🚵", keywords: ["person", "mountain", "biking", "sport"] },
  { emoji: "🚴", keywords: ["person", "biking", "sport"] },
  { emoji: "🏆", keywords: ["trophy", "win", "award", "prize"] },
  { emoji: "🥇", keywords: ["1st", "place", "medal", "win"] },
  { emoji: "🥈", keywords: ["2nd", "place", "medal", "win"] },
  { emoji: "🥉", keywords: ["3rd", "place", "medal", "win"] },
  { emoji: "🏅", keywords: ["sports", "medal", "win"] },
  { emoji: "🎖️", keywords: ["military", "medal", "win"] },
  { emoji: "🎯", keywords: ["bullseye", "target", "hit", "dart"] },
  // Objects & Symbols
  { emoji: "🔥", keywords: ["fire", "hot", "flame", "lit"] },
  { emoji: "✨", keywords: ["sparkles", "stars", "shine", "magic"] },
  { emoji: "💼", keywords: ["briefcase", "work", "business", "job"] },
  { emoji: "🚀", keywords: ["rocket", "space", "launch", "fast"] },
  { emoji: "👑", keywords: ["crown", "king", "queen", "royal"] },
  { emoji: "👔", keywords: ["necktie", "shirt", "suit", "formal"] },
  { emoji: "⚡️", keywords: ["high", "voltage", "lightning", "electricity"] },
  { emoji: "💎", keywords: ["gem", "stone", "diamond", "jewel"] },
  { emoji: "💡", keywords: ["light", "bulb", "idea", "smart"] },
  { emoji: "💯", keywords: ["hundred", "points", "perfect", "score"] },
  { emoji: "✅", keywords: ["check", "mark", "button", "yes", "done"] },
  { emoji: "❌", keywords: ["cross", "mark", "no", "wrong", "cancel"] },
  { emoji: "❤️", keywords: ["red", "heart", "love"] },
  { emoji: "💔", keywords: ["broken", "heart", "sad", "love"] },
  { emoji: "💀", keywords: ["skull", "dead", "death"] },
  { emoji: "👻", keywords: ["ghost", "boo", "scary"] },
  { emoji: "👽", keywords: ["alien", "ufo", "space"] },
  { emoji: "👾", keywords: ["alien", "monster", "game", "retro"] },
  { emoji: "🤖", keywords: ["robot", "bot", "ai"] },
  { emoji: "🎃", keywords: ["jack-o-lantern", "pumpkin", "halloween"] },
  { emoji: "⭐", keywords: ["star", "favorite", "rate"] },
  { emoji: "🌟", keywords: ["glowing", "star", "shine"] },
  { emoji: "📱", keywords: ["mobile", "phone", "cell", "smartphone"] },
  { emoji: "💻", keywords: ["laptop", "computer", "pc"] },
  { emoji: "⌚", keywords: ["watch", "time", "clock"] },
  { emoji: "🎧", keywords: ["headphone", "music", "listen"] },
  { emoji: "📷", keywords: ["camera", "photo", "picture"] },
  { emoji: "📸", keywords: ["camera", "with", "flash", "photo"] },
  { emoji: "💰", keywords: ["money", "bag", "cash", "rich"] },
  { emoji: "💵", keywords: ["dollar", "banknote", "money", "cash"] },
  { emoji: "💳", keywords: ["credit", "card", "money", "pay"] },
  { emoji: "🛒", keywords: ["shopping", "cart", "buy"] },
  { emoji: "🛍️", keywords: ["shopping", "bags", "buy"] },
  { emoji: "🎁", keywords: ["wrapped", "gift", "present", "birthday"] },
  { emoji: "🎉", keywords: ["party", "popper", "celebration"] },
  { emoji: "🎈", keywords: ["balloon", "party", "celebration"] },
  { emoji: "🎂", keywords: ["birthday", "cake", "party"] },
  { emoji: "🍔", keywords: ["hamburger", "food", "burger"] },
  { emoji: "🍕", keywords: ["pizza", "food", "slice"] },
  { emoji: "🍟", keywords: ["french", "fries", "food"] },
  { emoji: "🍩", keywords: ["doughnut", "food", "donut"] },
  { emoji: "☕", keywords: ["hot", "beverage", "coffee", "tea", "drink"] },
  { emoji: "🍺", keywords: ["beer", "mug", "drink"] },
  { emoji: "🍷", keywords: ["wine", "glass", "drink"] },
  { emoji: "🚗", keywords: ["automobile", "car", "vehicle"] },
  { emoji: "✈️", keywords: ["airplane", "flight", "travel"] },
  { emoji: "🏠", keywords: ["house", "home", "building"] },
  { emoji: "🏢", keywords: ["office", "building", "work"] },
  { emoji: "🏥", keywords: ["hospital", "medical", "health"] },
  { emoji: "📚", keywords: ["books", "read", "study"] },
  { emoji: "🎓", keywords: ["graduation", "cap", "school", "education"] }
];
